import React, { useState, useRef, useEffect } from 'react';
import { Search, Bell, LogOut, User, BellRing, RefreshCw, X, Shield, Command } from 'lucide-react';
import { Workspace, WORKSPACES } from '../config/navigation';
import { useNotifications } from '../context/NotificationContext';
import { useAuth } from '../context/AuthContext';
import { GlobalSearchModal } from './GlobalSearchModal';

export function TopNav({ activeWorkspace, setActiveWorkspace }: { activeWorkspace: Workspace, setActiveWorkspace: (w: Workspace) => void }) {
  const { notifications, isPanelOpen, togglePanel, addNotification } = useNotifications();
  const { user, logout, updateProfile } = useAuth();
  
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  
  // Edit Profile form state
  const [editName, setEditName] = useState(user?.name || '');
  const [editEmail, setEditEmail] = useState(user?.email || '');
  const [editPhone, setEditPhone] = useState(user?.phone || '');

  const menuRef = useRef<HTMLDivElement>(null);
  const avatarRef = useRef<HTMLButtonElement>(null);

  const unreadCount = notifications.filter(n => !n.read).length;

  // Handle click outside to close dropdown
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (
        menuRef.current && 
        !menuRef.current.contains(event.target as Node) &&
        avatarRef.current &&
        !avatarRef.current.contains(event.target as Node)
      ) {
        setIsMenuOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Global keydown listener for Cmd+K / Ctrl+K / / key search trigger
  useEffect(() => {
    const handleGlobalKeyDown = (e: KeyboardEvent) => {
      // Don't intercept if user is typing in an input/textarea
      const activeElement = document.activeElement;
      const isInput = activeElement?.tagName === 'INPUT' || activeElement?.tagName === 'TEXTAREA';

      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setIsSearchOpen(prev => !prev);
      } else if (e.key === '/' && !isInput && !isSearchOpen) {
        e.preventDefault();
        setIsSearchOpen(true);
      }
    };

    window.addEventListener('keydown', handleGlobalKeyDown);
    return () => window.removeEventListener('keydown', handleGlobalKeyDown);
  }, [isSearchOpen]);

  // Update edit form when user context changes
  useEffect(() => {
    if (user) {
      setEditName(user.name);
      setEditEmail(user.email);
      setEditPhone(user.phone);
    }
  }, [user, isEditModalOpen]);

  const handleSaveProfile = (e: React.FormEvent) => {
    e.preventDefault();
    updateProfile({
      name: editName,
      email: editEmail,
      phone: editPhone,
    });
    
    addNotification({
      type: 'SYSTEM',
      title: 'Profile Updated',
      message: 'Your personal CRM operator profile was updated successfully.',
      date: 'Just now',
    });

    setIsEditModalOpen(false);
    setIsMenuOpen(false);
  };

  const handleTriggerLiveAlert = () => {
    addNotification({
      type: 'SYSTEM',
      title: 'Sandbox Alert Triggered',
      message: `On-demand event generated by ${user?.name || 'User'} from the Command Panel.`,
      date: 'Just now',
    });
    setIsMenuOpen(false);
  };

  const handleResetData = () => {
    if (confirm('Are you sure you want to reset all CRM demo data? Custom entries will be cleared.')) {
      localStorage.removeItem('sp_crm_enquiries');
      localStorage.removeItem('sp_crm_tasks');
      localStorage.removeItem('sp_crm_activities');
      localStorage.removeItem('sp_crm_quotations');
      localStorage.removeItem('sp_crm_leads');
      window.location.reload();
    }
  };

  return (
    <header className="flex flex-col md:flex-row items-start md:items-center justify-between py-6 gap-6 md:gap-0 relative">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 bg-[#1a1a1a] rounded-xl flex items-center justify-center text-white relative overflow-hidden shadow-sm">
          <div className="absolute top-0 right-0 w-6 h-6 bg-blue-500/20 rounded-bl-xl"></div>
          <span className="font-display font-bold text-lg tracking-tighter relative z-10">SP</span>
        </div>
        <span className="font-display font-semibold text-2xl tracking-tight">SP CRM</span>
      </div>

      <nav className="flex flex-wrap items-center gap-1 md:gap-2 text-sm font-medium">
        {WORKSPACES.map(link => (
          <button 
            key={link}
            onClick={() => setActiveWorkspace(link)}
            className={`px-5 py-2.5 rounded-full transition-all ${
              link === activeWorkspace 
                ? 'bg-[#1a1a1a] text-white shadow-lg shadow-black/10' 
                : 'text-neutral-600 hover:bg-white/50'
            }`}
          >
            {link}
          </button>
        ))}
      </nav>

      <div className="flex items-center gap-2.5 relative">
        {/* Interactive Global Search Bar Trigger Pill */}
        <button 
          onClick={() => setIsSearchOpen(true)}
          className="h-10 px-3.5 rounded-full bg-white/70 hover:bg-white transition-all border border-neutral-200/80 hover:border-neutral-300 text-neutral-500 hover:text-neutral-900 shadow-2xs flex items-center gap-2.5 group cursor-pointer"
          title="Search entire CRM (Cmd + K or /)"
        >
          <Search size={16} className="text-neutral-400 group-hover:text-neutral-700 transition-colors shrink-0" />
          <span className="text-xs font-semibold hidden lg:inline text-neutral-500 group-hover:text-neutral-800 transition-colors">
            Search entire CRM...
          </span>
          <span className="hidden sm:flex items-center gap-0.5 text-[10px] font-extrabold text-neutral-400 bg-neutral-100 group-hover:bg-neutral-200/80 px-1.5 py-0.5 rounded-md border border-neutral-200/60 transition-colors">
            <Command size={10} /> K
          </span>
        </button>
        
        {/* Notifications Trigger */}
        <button 
          onClick={togglePanel}
          className={`w-10 h-10 flex items-center justify-center rounded-full transition-colors border relative ${isPanelOpen ? 'bg-white border-blue-200 shadow-sm text-blue-600' : 'bg-white/40 hover:bg-white/60 border-white/60 text-neutral-600'}`}
          title="Notification Desk"
        >
          <Bell size={18} />
          {unreadCount > 0 && (
            <span className="absolute top-2 right-2 w-2.5 h-2.5 bg-blue-500 rounded-full border-2 border-white animate-pulse"></span>
          )}
        </button>

        {/* User Profile Trigger Button (SP Initials Badge - NO PHOTO) */}
        <button 
          ref={avatarRef}
          onClick={() => setIsMenuOpen(!isMenuOpen)}
          className="relative focus:outline-none focus:ring-2 focus:ring-blue-500 rounded-full ml-1 transition-transform active:scale-95 group"
          title="User Account Menu"
        >
          <div className="w-10 h-10 rounded-full bg-[#1a1a1a] text-white flex items-center justify-center font-bold text-xs tracking-wider border-2 border-white shadow-sm group-hover:bg-black transition-colors">
            SP
          </div>
          <div className="absolute -bottom-0.5 -right-0.5 w-3.5 h-3.5 bg-emerald-500 border-2 border-white rounded-full"></div>
        </button>

        {/* PROFILE DROP-DOWN WINDOW */}
        {isMenuOpen && (
          <div 
            ref={menuRef}
            className="absolute right-0 top-14 w-80 bg-white border border-neutral-200/80 rounded-2xl shadow-xl z-50 p-4 animate-in fade-in slide-in-from-top-4 duration-200"
          >
            {/* User details header card - Initial Badge */}
            <div className="flex items-center gap-3 pb-3.5 mb-3.5 border-b border-neutral-100">
              <div className="w-11 h-11 rounded-full bg-[#1a1a1a] text-white flex items-center justify-center font-bold text-sm tracking-wider border border-neutral-200 shadow-2xs shrink-0">
                SP
              </div>
              <div className="min-w-0 flex-1">
                <h4 className="text-sm font-bold text-neutral-900 truncate leading-tight">{user?.name || 'Shakir Pathan'}</h4>
                <p className="text-[11px] text-neutral-500 truncate mt-0.5">{user?.email || 'shakir@sp.com'}</p>
                <div className="mt-1.5 flex items-center gap-1.5">
                  <span className="text-[9px] font-bold bg-neutral-100 text-neutral-700 px-1.5 py-0.5 rounded flex items-center gap-1">
                    <Shield size={9} /> {user?.role || 'Administrator'}
                  </span>
                </div>
              </div>
            </div>

            {/* Actions List */}
            <div className="space-y-1">
              <button
                type="button"
                onClick={() => {
                  setIsEditModalOpen(true);
                  setIsMenuOpen(false);
                }}
                className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-neutral-700 hover:text-neutral-900 hover:bg-neutral-50 font-semibold text-xs text-left transition-colors"
              >
                <User size={15} className="text-neutral-400" />
                <span>Edit Profile Information</span>
              </button>

              <button
                type="button"
                onClick={handleTriggerLiveAlert}
                className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-neutral-700 hover:text-blue-700 hover:bg-blue-50/50 font-semibold text-xs text-left transition-colors"
              >
                <BellRing size={15} className="text-neutral-400" />
                <span>Trigger Live Demo Notification</span>
              </button>

              <button
                type="button"
                onClick={handleResetData}
                className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-rose-600 hover:bg-rose-50/50 font-semibold text-xs text-left transition-colors"
              >
                <RefreshCw size={15} className="text-rose-400" />
                <span>Reset CRM Database State</span>
              </button>

              <div className="border-t border-neutral-100 my-2 pt-2">
                <button
                  type="button"
                  onClick={logout}
                  className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-neutral-700 hover:text-neutral-950 hover:bg-neutral-50 font-bold text-xs text-left transition-colors"
                >
                  <LogOut size={15} className="text-neutral-400" />
                  <span>Logout Securely</span>
                </button>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* GLOBAL SEARCH COMMAND PALETTE MODAL */}
      <GlobalSearchModal
        isOpen={isSearchOpen}
        onClose={() => setIsSearchOpen(false)}
      />

      {/* EDIT PROFILE DIALOG MODAL */}
      {isEditModalOpen && (
        <div className="fixed inset-0 bg-neutral-950/40 backdrop-blur-xs flex items-center justify-center z-[100] p-4">
          <div className="bg-white border border-neutral-200/60 rounded-3xl w-full max-w-md shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
            {/* Header */}
            <div className="px-6 py-4 border-b border-neutral-100 flex items-center justify-between bg-neutral-50/80">
              <div>
                <h3 className="font-bold text-neutral-900 text-base">Edit User Profile</h3>
                <p className="text-xs text-neutral-500 mt-0.5">Customize your operator metadata</p>
              </div>
              <button 
                onClick={() => setIsEditModalOpen(false)}
                className="w-8 h-8 rounded-full bg-white hover:bg-neutral-100 border border-neutral-200/50 flex items-center justify-center text-neutral-500 hover:text-neutral-800 transition-colors"
              >
                <X size={16} />
              </button>
            </div>

            {/* Form */}
            <form onSubmit={handleSaveProfile} className="p-6 space-y-4">
              {/* Initials Badge Display (NO PHOTO) */}
              <div className="flex items-center gap-4 bg-neutral-50 p-3 rounded-2xl border border-neutral-200/60">
                <div className="w-12 h-12 rounded-full bg-[#1a1a1a] text-white flex items-center justify-center font-bold text-base tracking-wider border border-neutral-200 shadow-sm shrink-0">
                  SP
                </div>
                <div>
                  <h4 className="text-xs font-bold text-neutral-800">SP CRM Operator Badge</h4>
                  <p className="text-[11px] text-neutral-500 mt-0.5">Standardized initials avatar badge</p>
                </div>
              </div>

              {/* Full Name */}
              <div className="space-y-1">
                <label className="block text-xs font-bold text-neutral-600 ml-1">Full Name</label>
                <input
                  type="text"
                  value={editName}
                  onChange={(e) => setEditName(e.target.value)}
                  placeholder="e.g. Shakir Pathan"
                  className="w-full px-4 py-2.5 bg-neutral-50 border border-neutral-200 focus:border-neutral-900 focus:bg-white rounded-xl text-xs text-neutral-800 outline-none font-medium"
                  required
                />
              </div>

              {/* Email */}
              <div className="space-y-1">
                <label className="block text-xs font-bold text-neutral-600 ml-1">Email Address</label>
                <input
                  type="email"
                  value={editEmail}
                  onChange={(e) => setEditEmail(e.target.value)}
                  placeholder="e.g. shakir@sp.com"
                  className="w-full px-4 py-2.5 bg-neutral-50 border border-neutral-200 focus:border-neutral-900 focus:bg-white rounded-xl text-xs text-neutral-800 outline-none font-medium"
                  required
                />
              </div>

              {/* Phone */}
              <div className="space-y-1">
                <label className="block text-xs font-bold text-neutral-600 ml-1">Phone Number</label>
                <input
                  type="text"
                  value={editPhone}
                  onChange={(e) => setEditPhone(e.target.value)}
                  placeholder="e.g. +91 98765 43210"
                  className="w-full px-4 py-2.5 bg-neutral-50 border border-neutral-200 focus:border-neutral-900 focus:bg-white rounded-xl text-xs text-neutral-800 outline-none font-medium"
                />
              </div>

              {/* Footer Buttons */}
              <div className="pt-4 flex items-center justify-end gap-2 border-t border-neutral-100">
                <button
                  type="button"
                  onClick={() => setIsEditModalOpen(false)}
                  className="px-4 py-2.5 text-neutral-600 hover:text-neutral-800 hover:bg-neutral-100 rounded-xl text-xs font-bold transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 bg-neutral-900 text-white hover:bg-black rounded-xl text-xs font-bold transition-all shadow-md"
                >
                  Save Profile
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </header>
  );
}


